# This is a basic workflow to help you get started with Actions

name: Update AOC Badges

# Controls when the workflow will run
on:
  schedule:                                      # run workflow based on schedule
    - cron: '6 5 1-25 12 *'                      # from the 1. December till 25. December every day at 5:06am (avoid load at full hours)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: AoC-badges
        # You may pin to the exact commit or the version.
        # uses: J0B10/aoc-badges-action@75cd611df531bd9aa0675cae13be418d73cbdf76
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          # Your session code for login. Retrive it from your browser cookies. Make sure you use a secret to not leak this to public.

          session: ${{ secrets.AOC_SESSION }}
          # Your unique userid on adventofcode.com, obtain it from **YOUR** private leaderboard url (its the number at the end of the url).

          userid: ${{ secrets.AOC_USERID }}
          # The year for which the stats should be retrived.  If not speified, the current year (from system time) is used.

      - uses: stefanzweifel/git-auto-commit-action@v4     # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: README.md
